In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv(r'E:\ML\student placement model\test.csv')

In [4]:
df

,Student_ID,Age,Gender,Degree,Branch,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_Status
0,15202,23,Male,B.Tech,Civil,7.32,2,4,5,6,56,6,1,0,Placed
1,4573,24,Female,MCA,ME,4.76,0,1,1,4,37,4,0,3,Not Placed
2,34424,20,Male,BCA,ME,6.16,0,3,3,8,68,6,1,3,Not Placed
3,38881,19,Male,B.Sc,IT,8.77,2,5,8,5,83,6,3,0,Placed
4,30191,23,Male,B.Tech,ME,7.63,0,3,4,6,66,7,1,0,Not Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,9362,20,Male,MCA,Civil,7.84,2,5,9,7,68,6,3,1,Placed
49996,8940,19,Female,B.Sc,ME,8.28,1,4,6,5,74,5,2,0,Placed
49997,13097,20,Female,B.Sc,Civil,8.88,0,4,4,5,83,4,2,0,Not Placed
49998,12958,24,Female,MCA,ECE,5.90,1,3,6,6,60,2,2,1,Not Placed
49999,9565,23,Female,B.Tech,ME,6.28,0,4,6,6,64,7,2,3,Not Placed

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Student_ID            50000 non-null  int64
 1   Age                   50000 non-null  int64
 2   Gender                50000 non-null  object
 3   Degree                50000 non-null  object
 4   Branch                50000 non-null  object
 5   CGPA                  50000 non-null  float64
 6   Internships           50000 non-null  int64
 7   Projects              50000 non-null  int64
 8   Coding_Skills         50000 non-null  int64
 9   Communication_Skills  50000 non-null  int64
 10  Aptitude_Test_Score   50000 non-null  int64
 11  Soft_Skills_Rating    50000 non-null  int64
 12  Certifications        50000 non-null  int64
 13  Backlogs              50000 non-null  int64
 14  Placement_Status      50000 non-null  object
dtypes: float64(1), int64(10), object(4)
memory usage: 5.7+ MB

In [6]:
df = df.drop(columns=['Student_ID'])

In [7]:
df.head()

,Age,Gender,Degree,Branch,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_Status
0,23,Male,B.Tech,Civil,7.32,2,4,5,6,56,6,1,0,Placed
1,24,Female,MCA,ME,4.76,0,1,1,4,37,4,0,3,Not Placed
2,20,Male,BCA,ME,6.16,0,3,3,8,68,6,1,3,Not Placed
3,19,Male,B.Sc,IT,8.77,2,5,8,5,83,6,3,0,Placed
4,23,Male,B.Tech,ME,7.63,0,3,4,6,66,7,1,0,Not Placed

In [8]:
df['Degree'].value_counts()

Degree
B.Sc      12613
MCA       12575
B.Tech    12543
BCA       12269
Name: count, dtype: int64

In [9]:
df['Branch'].value_counts()

Branch
ME       10038
ECE      10030
CSE       9993
IT        9983
Civil     9956
Name: count, dtype: int64

In [10]:
try:
    from sklearn.preprocessing import LabelEncoder
except ModuleNotFoundError:
    import sys, subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "scikit-learn"])
    from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Degree'] = le.fit_transform(df['Degree'])
df['Gender'] = le.fit_transform(df['Gender'])
df['Branch'] = le.fit_transform(df['Branch'])
df['Placement_Status'] = le.fit_transform(df['Placement_Status'])
le = LabelEncoder()
df['Degree'] = le.fit_transform(df['Degree'])
df['Gender'] = le.fit_transform(df['Gender'])
df['Branch'] = le.fit_transform(df['Branch'])
df['Placement_Status'] = le.fit_transform(df['Placement_Status'])

In [11]:
df

,Age,Gender,Degree,Branch,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_Status
0,23,1,1,1,7.32,2,4,5,6,56,6,1,0,1
1,24,0,3,4,4.76,0,1,1,4,37,4,0,3,0
2,20,1,2,4,6.16,0,3,3,8,68,6,1,3,0
3,19,1,0,3,8.77,2,5,8,5,83,6,3,0,1
4,23,1,1,4,7.63,0,3,4,6,66,7,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20,1,3,1,7.84,2,5,9,7,68,6,3,1,1
49996,19,0,0,4,8.28,1,4,6,5,74,5,2,0,1
49997,20,0,0,1,8.88,0,4,4,5,83,4,2,0,0
49998,24,0,3,2,5.90,1,3,6,6,60,2,2,1,0
49999,23,0,1,4,6.28,0,4,6,6,64,7,2,3,0

In [12]:
from sklearn.model_selection import train_test_split
X = df.drop(columns=['Placement_Status'])
Y = df['Placement_Status']

In [13]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [14]:
from sklearn.linear_model import LogisticRegression
model_LR = LogisticRegression()
model_LR.fit(X_train,Y_train)

LogisticRegression()

In [15]:
Y_pred=model_LR.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

accuracy_score(Y_test,Y_pred)

0.8666

In [17]:
confusion_matrix(Y_test,Y_pred)

array([[5702,  680],
       [ 654, 2964]])

In [18]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.90      0.89      0.90      6382
           1       0.81      0.82      0.82      3618

    accuracy                           0.87     10000
   macro avg       0.86      0.86      0.86     10000
weighted avg       0.87      0.87      0.87     10000

In [19]:
importance = model_LR.coef_[0]

for i,v in enumerate(importance):
    print(X.columns[i],":",v)

Age : -0.05926326204198289
Gender : 0.01648248994086036
Degree : -0.07726945520667565
Branch : 0.12015761628734564
CGPA : -0.34161145013243804
Internships : 0.05227922907523856
Projects : 0.6961516793464164
Coding_Skills : -0.13080464517580437
Communication_Skills : 0.8964187326202692
Aptitude_Test_Score : 0.008440149980509562
Soft_Skills_Rating : -0.16633466228476662
Certifications : 2.050143253903849
Backlogs : -1.970090315799659

In [20]:
from sklearn.naive_bayes import GaussianNB
model_NB = GaussianNB()
model_NB.fit(X_train,Y_train)

GaussianNB()

In [21]:
y_pred = model_NB.predict(X_test)

In [22]:
print(y_pred)

[1 0 1 ... 0 1 0]

In [23]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

accuracy_score(Y_test,Y_pred)

0.8666

In [24]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.90      0.89      0.90      6382
           1       0.81      0.82      0.82      3618

    accuracy                           0.87     10000
   macro avg       0.86      0.86      0.86     10000
weighted avg       0.87      0.87      0.87     10000

In [25]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN = KNeighborsClassifier(n_neighbors=9)
model_KNN.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=9)

In [26]:
y_pred=model_KNN.predict(X_test)

In [27]:
print(y_pred)

[1 0 1 ... 0 1 0]

In [28]:
print(accuracy_score(Y_test,y_pred))

0.9305

In [29]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.91      0.94      6382
           1       0.86      0.96      0.91      3618

    accuracy                           0.93     10000
   macro avg       0.92      0.94      0.93     10000
weighted avg       0.94      0.93      0.93     10000

In [30]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train,Y_train)

DecisionTreeClassifier()

In [31]:
y_pred=model.predict(X_test)

In [32]:
print(y_pred)

[1 0 1 ... 0 1 0]

In [33]:
print(accuracy_score(Y_test,y_pred))

1.0

In [34]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6382
           1       1.00      1.00      1.00      3618

    accuracy                           1.00     10000
   macro avg       1.00      1.00      1.00     10000
weighted avg       1.00      1.00      1.00     10000

In [35]:
print(confusion_matrix(Y_test,y_pred))

[[6382    0]
 [   0 3618]]

In [36]:
df

,Age,Gender,Degree,Branch,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_Status
0,23,1,1,1,7.32,2,4,5,6,56,6,1,0,1
1,24,0,3,4,4.76,0,1,1,4,37,4,0,3,0
2,20,1,2,4,6.16,0,3,3,8,68,6,1,3,0
3,19,1,0,3,8.77,2,5,8,5,83,6,3,0,1
4,23,1,1,4,7.63,0,3,4,6,66,7,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20,1,3,1,7.84,2,5,9,7,68,6,3,1,1
49996,19,0,0,4,8.28,1,4,6,5,74,5,2,0,1
49997,20,0,0,1,8.88,0,4,4,5,83,4,2,0,0
49998,24,0,3,2,5.90,1,3,6,6,60,2,2,1,0
49999,23,0,1,4,6.28,0,4,6,6,64,7,2,3,0

In [37]:
x = df.drop(columns=['Placement_Status'])
y = df['Placement_Status']

In [38]:
from sklearn.model_selection import cross_val_score

In [39]:
scores = cross_val_score(model_KNN,x,y,cv=5,scoring="accuracy")

In [40]:
print(scores)

[0.9277 0.9343 0.9329 0.9339 0.9348]

In [41]:
print(scores.mean())

0.93272

In [42]:
from sklearn.model_selection import GridSearchCV

In [43]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

model_KNN = KNeighborsClassifier()

classifier = GridSearchCV(
    estimator=model_KNN,
    param_grid={
        'n_neighbors': [1,2,3,4,5,6,7,8,9,10],
        'metric': ['minkowski', 'euclidean']
    },
    cv=5,
    scoring='accuracy',
    n_jobs=-1   # use all CPU cores (faster)
)

classifier.fit(X_train, Y_train)

print(classifier.best_params_)
print(classifier.best_score_)

{'metric': 'minkowski', 'n_neighbors': 10}
0.938175

In [44]:
classifier.cv_results_

{'mean_fit_time': array([0.62181749, 0.56991792, 0.59292593, 0.48649316, 0.49816651,
        0.4947422 , 0.52149911, 0.47064452, 0.48804393, 0.56219301,
        0.60277853, 0.50300107, 0.50150065, 0.93201408, 0.6603013 ,
        0.51680489, 0.46122994, 0.55131755, 0.56916413, 0.61521788]),
 'std_fit_time': array([0.06049298, 0.09348609, 0.0295471 , 0.08100499, 0.06390327,
        0.04535811, 0.04052048, 0.02521452, 0.02185224, 0.02660409,
        0.0399311 , 0.05175811, 0.01167294, 0.32198243, 0.08663896,
        0.01872649, 0.07670266, 0.02481627, 0.02988126, 0.06243565]),
 'mean_score_time': array([2.54917116, 3.06892867, 3.51365762, 3.57546725, 3.76050782,
        3.87646356, 4.0763927 , 4.59156756, 4.69971433, 4.87931757,
        2.51977377, 3.78425694, 3.86113605, 3.97749882, 3.82958002,
        4.07691097, 4.07695899, 4.75519776, 4.44004769, 3.78042016]),
 'std_score_time': array([0.11475555, 0.20292403, 0.06975475, 0.28584173, 0.23917602,
        0.18247316, 0.16212081, 0.21027589, 0.10540021, 0.21472229,
        0.06677153, 0.51558977, 0.07791023, 0.39412922, 0.07284219,
        0.08510847, 0.47274089, 0.08279953, 0.16994169, 0.16083414]),
 'param_metric': masked_array(data=['minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8,
                    9, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'params': [{'metric': 'minkowski', 'n_neighbors': 1},
  {'metric': 'minkowski', 'n_neighbors': 2},
  {'metric': 'minkowski', 'n_neighbors': 3},
  {'metric': 'minkowski', 'n_neighbors': 4},
  {'metric': 'minkowski', 'n_neighbors': 5},
  {'metric': 'minkowski', 'n_neighbors': 6},
  {'metric': 'minkowski', 'n_neighbors': 7},
  {'metric': 'minkowski', 'n_neighbors': 8},
  {'metric': 'minkowski', 'n_neighbors': 9},
  {'metric': 'minkowski', 'n_neighbors': 10},
  {'metric': 'euclidean', 'n_neighbors': 1},
  {'metric': 'euclidean', 'n_neighbors': 2},
  {'metric': 'euclidean', 'n_neighbors': 3},
  {'metric': 'euclidean', 'n_neighbors': 4},
  {'metric': 'euclidean', 'n_neighbors': 5},
  {'metric': 'euclidean', 'n_neighbors': 6},
  {'metric': 'euclidean', 'n_neighbors': 7},
  {'metric': 'euclidean', 'n_neighbors': 8},
  {'metric': 'euclidean', 'n_neighbors': 9},
  {'metric': 'euclidean', 'n_neighbors': 10}],
 'split0_test_score': array([0.8975  , 0.9035  , 0.91875 , 0.925125, 0.92525 , 0.9305  ,
        0.92475 , 0.935875, 0.92875 , 0.937625, 0.8975  , 0.9035  ,
        0.91875 , 0.925125, 0.92525 , 0.9305  , 0.92475 , 0.935875,
        0.92875 , 0.937625]),
 'split1_test_score': array([0.89175 , 0.901375, 0.91325 , 0.923125, 0.92325 , 0.93375 ,
        0.927375, 0.937   , 0.92675 , 0.93675 , 0.89175 , 0.901375,
        0.91325 , 0.923125, 0.92325 , 0.93375 , 0.927375, 0.937   ,
        0.92675 , 0.93675 ]),
 'split2_test_score': array([0.900125, 0.903125, 0.92225 , 0.925   , 0.927125, 0.932875,
        0.92825 , 0.932375, 0.930125, 0.93825 , 0.900125, 0.903125,
        0.92225 , 0.925   , 0.927125, 0.932875, 0.92825 , 0.932375,
        0.930125, 0.93825 ]),
 'split3_test_score': array([0.89925 , 0.898125, 0.921125, 0.924875, 0.9275  , 0.93575 ,
        0.932375, 0.937875, 0.933   , 0.9415  , 0.89925 , 0.898125,
        0.921125, 0.924875, 0.9275  , 0.93575 , 0.932375, 0.937875,
        0.933   , 0.9415  ]),
 'split4_test_score': array([0.901875, 0.9015  , 0.916875, 0.924125, 0.92475 , 0.93025 ,
        0.92825 , 0.93425 , 0.929625, 0.93675 , 0.901875, 0.9015  ,
        0.916875, 0.924125, 0.92475 , 0.93025 , 0.92825 , 0.93425 ,
        0.929625, 0.93675 ]),
 'mean_test_score': array([0.8981  , 0.901525, 0.91845 , 0.92445 , 0.925575, 0.932625,
        0.9282  , 0.935475, 0.92965 , 0.938175, 0.8981  , 0.901525,
        0.91845 , 0.92445 , 0.925575, 0.932625, 0.9282  , 0.935475,
        0.92965 , 0.938175]),
 'std_test_score': array([0.00347437, 0.00189967, 0.0032002 , 0.00074833, 0.00156844,
        0.00206155, 0.00245026, 0.00196755, 0.00203316, 0.00175642,
        0.00347437, 0.00189967, 0.0032002 , 0.00074833, 0.00156844,
        0.00206155, 0.00245026, 0.00196755, 0.00203316, 0.00175642]),
 'rank_test_score': array([19, 17, 15, 13, 11,  5,  9,  3,  7,  1, 19, 17, 15, 13, 11,  5,  9,
         3,  7,  1], dtype=int32)}

In [45]:
results=pd.DataFrame(classifier.cv_results_)

In [46]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.621817,0.060493,2.549171,0.114756,minkowski,1,"{'metric': 'minkowski', 'n_neighbors': 1}",0.897500,0.891750,0.900125,0.899250,0.901875,0.898100,0.003474,19
1,0.569918,0.093486,3.068929,0.202924,minkowski,2,"{'metric': 'minkowski', 'n_neighbors': 2}",0.903500,0.901375,0.903125,0.898125,0.901500,0.901525,0.001900,17
2,0.592926,0.029547,3.513658,0.069755,minkowski,3,"{'metric': 'minkowski', 'n_neighbors': 3}",0.918750,0.913250,0.922250,0.921125,0.916875,0.918450,0.003200,15
3,0.486493,0.081005,3.575467,0.285842,minkowski,4,"{'metric': 'minkowski', 'n_neighbors': 4}",0.925125,0.923125,0.925000,0.924875,0.924125,0.924450,0.000748,13
4,0.498167,0.063903,3.760508,0.239176,minkowski,5,"{'metric': 'minkowski', 'n_neighbors': 5}",0.925250,0.923250,0.927125,0.927500,0.924750,0.925575,0.001568,11
5,0.494742,0.045358,3.876464,0.182473,minkowski,6,"{'metric': 'minkowski', 'n_neighbors': 6}",0.930500,0.933750,0.932875,0.935750,0.930250,0.932625,0.002062,5
6,0.521499,0.040520,4.076393,0.162121,minkowski,7,"{'metric': 'minkowski', 'n_neighbors': 7}",0.924750,0.927375,0.928250,0.932375,0.928250,0.928200,0.002450,9
7,0.470645,0.025215,4.591568,0.210276,minkowski,8,"{'metric': 'minkowski', 'n_neighbors': 8}",0.935875,0.937000,0.932375,0.937875,0.934250,0.935475,0.001968,3
8,0.488044,0.021852,4.699714,0.105400,minkowski,9,"{'metric': 'minkowski', 'n_neighbors': 9}",0.928750,0.926750,0.930125,0.933000,0.929625,0.929650,0.002033,7
9,0.562193,0.026604,4.879318,0.214722,minkowski,10,"{'metric': 'minkowski', 'n_neighbors': 10}",0.937625,0.936750,0.938250,0.941500,0.936750,0.938175,0.001756,1
10,0.602779,0.039931,2.519774,0.066772,euclidean,1,"{'metric': 'euclidean', 'n_neighbors': 1}",0.897500,0.891750,0.900125,0.899250,0.901875,0.898100,0.003474,19
11,0.503001,0.051758,3.784257,0.515590,euclidean,2,"{'metric': 'euclidean', 'n_neighbors': 2}",0.903500,0.901375,0.903125,0.898125,0.901500,0.901525,0.001900,17
12,0.501501,0.011673,3.861136,0.077910,euclidean,3,"{'metric': 'euclidean', 'n_neighbors': 3}",0.918750,0.913250,0.922250,0.921125,0.916875,0.918450,0.003200,15
13,0.932014,0.321982,3.977499,0.394129,euclidean,4,"{'metric': 'euclidean', 'n_neighbors': 4}",0.925125,0.923125,0.925000,0.924875,0.924125,0.924450,0.000748,13
14,0.660301,0.086639,3.829580,0.072842,euclidean,5,"{'metric': 'euclidean', 'n_neighbors': 5}",0.925250,0.923250,0.927125,0.927500,0.924750,0.925575,0.001568,11
15,0.516805,0.018726,4.076911,0.085108,euclidean,6,"{'metric': 'euclidean', 'n_neighbors': 6}",0.930500,0.933750,0.932875,0.935750,0.930250,0.932625,0.002062,5
16,0.461230,0.076703,4.076959,0.472741,euclidean,7,"{'metric': 'euclidean', 'n_neighbors': 7}",0.924750,0.927375,0.928250,0.932375,0.928250,0.928200,0.002450,9
17,0.551318,0.024816,4.755198,0.082800,euclidean,8,"{'metric': 'euclidean', 'n_neighbors': 8}",0.935875,0.937000,0.932375,0.937875,0.934250,0.935475,0.001968,3
18,0.569164,0.029881,4.440048,0.169942,euclidean,9,"{'metric': 'euclidean', 'n_neighbors': 9}",0.928750,0.926750,0.930125,0.933000,0.929625,0.929650,0.002033,7
19,0.615218,0.062436,3.780420,0.160834,euclidean,10,"{'metric': 'euclidean', 'n_neighbors': 10}",0.937625,0.936750,0.938250,0.941500,0.936750,0.938175,0.001756,1

In [47]:
df

,Age,Gender,Degree,Branch,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_Status
0,23,1,1,1,7.32,2,4,5,6,56,6,1,0,1
1,24,0,3,4,4.76,0,1,1,4,37,4,0,3,0
2,20,1,2,4,6.16,0,3,3,8,68,6,1,3,0
3,19,1,0,3,8.77,2,5,8,5,83,6,3,0,1
4,23,1,1,4,7.63,0,3,4,6,66,7,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20,1,3,1,7.84,2,5,9,7,68,6,3,1,1
49996,19,0,0,4,8.28,1,4,6,5,74,5,2,0,1
49997,20,0,0,1,8.88,0,4,4,5,83,4,2,0,0
49998,24,0,3,2,5.90,1,3,6,6,60,2,2,1,0
49999,23,0,1,4,6.28,0,4,6,6,64,7,2,3,0

In [48]:
x = df.drop(columns=['Placement_Status'])
y = df['Placement_Status']

In [49]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [50]:
x_scaled

array([[ 1.00249934,  1.00260339, -0.44241708, ...,  0.40151439,
        -1.23339049, -0.91387049],
       [ 1.50374901, -0.99740337,  1.34109126, ..., -1.21248405,
        -2.77208968,  2.17945172],
       [-0.50124967,  1.00260339,  0.44933709, ...,  0.40151439,
        -1.23339049,  2.17945172],
       ...,
       [-0.50124967, -0.99740337, -1.33417125, ..., -1.21248405,
         0.30530869, -0.91387049],
       [ 1.50374901, -0.99740337,  1.34109126, ..., -2.8264825 ,
         0.30530869,  0.11723691],
       [ 1.00249934, -0.99740337, -0.44241708, ...,  1.20851362,
         0.30530869,  2.17945172]], shape=(50000, 13))

In [51]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x_scaled,y,test_size=0.2,random_state=42)

In [52]:
from sklearn.linear_model import LogisticRegression
model_LR = LogisticRegression()
model_LR.fit(X_train,Y_train)

LogisticRegression()

In [53]:
y_pred=model_LR.predict(X_test)

In [54]:
accuracy_score(Y_test,y_pred)

0.8686

In [55]:
from sklearn.ensemble import StackingClassifier

In [56]:
base_learners = [
    ('dt', DecisionTreeClassifier()),
    ('knn', KNeighborsClassifier(n_neighbors=9)),
    ('nb', GaussianNB())
]

In [57]:
meta_learner = LogisticRegression(random_state=42,max_iter=1000)

In [58]:
stacking_clf = StackingClassifier(estimators=base_learners, final_estimator=meta_learner)

In [59]:
stacking_clf.fit(X_train, Y_train)

StackingClassifier(estimators=[('dt', DecisionTreeClassifier()),
                               ('knn', KNeighborsClassifier(n_neighbors=9)),
                               ('nb', GaussianNB())],
                   final_estimator=LogisticRegression(max_iter=1000,
                                                      random_state=42))

In [60]:
y_pred=stacking_clf.predict(X_test)

In [61]:
accuracy_score(Y_test,y_pred)

1.0

In [62]:
from sklearn.ensemble import RandomForestClassifier
model_RF = RandomForestClassifier(n_estimators=100, random_state=42,max_depth=None)

In [63]:
model_RF.fit(X_train,Y_train)

RandomForestClassifier(random_state=42)

In [64]:
y_rf_predict = model_RF.predict(X_train)

In [65]:
y_rf_predict = model_RF.predict(X_test)
accuracy_score(Y_test, y_rf_predict)

1.0

In [66]:
import joblib

joblib.dump(model_LR,'placement_model.pkl')

joblib.dump(scaler,'scaler.pkl')

['scaler.pkl']

In [67]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Models
models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC()
}

# Compare accuracies
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    print(f"{name}: {acc:.4f}")

Logistic Regression: 0.8666
Decision Tree: 1.0000
Random Forest: 1.0000
SVM: 0.8786

In [ ]:
results = []
results.append(("Logistic Regression", accuracy_score(y_test, model_LR.predict(X_test))))
model_KNN.fit(X_train, Y_train)
results.append(("KNN", accuracy_score(Y_test, model_KNN.predict(X_test))))
results.append(("Decision Tree", accuracy_score(y_test, model.predict(X_test))))
results.append(("Random Forest", accuracy_score(y_test, model_RF.predict(X_test))))

NotFittedError: This KNeighborsClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.